### ISSUE TITLE
Pull locations of nearby gas stations (5 miles away maximum?)

### ISSUE THREAD

**Issue by NShively** [napaunderground/FuelFinder#11]
https://developers.google.com/places/webservice/search

**Comment by MorroMat** [comment]
Why would we limit it to just 5 miles away? To make the computation easier? Or is it just the logic of driving more than 5 miles is gonna cost you more in gas than any of the close by ones?

**Comment by NShively** [comment]
yes

**Comment by NShively** [comment]
it is very good to be in going with work you now

**Comment by NShively** [comment]
But in all seriousness, 5 miles was just a random number I put out, could be replaced by anything. We need a reasonable number so that we can limit the gas stations we search..

**Comment by NShively** [comment]
Google Places API - Search seems like a good idea. 
https://developers.google.com/places/webservice/search
Automatically has a field to pull only the places around you within a radius.

**Comment by napaunderground** [comment]
Sounds good.
